name: skorch
channels:
  - defaults
  - pytorch
dependencies:
  - _libgcc_mutex=0.1
  - absl-py=0.12.0
  - aiohttp=3.7.4
  - alabaster=0.7.12
  - astroid=2.5
  - async-timeout=3.0.1
  - attrs=20.3.0
  - babel=2.9.0
  - blas=1.0
  - blinker=1.4
  - brotlipy=0.7.0
  - c-ares=1.17.1
  - ca-certificates=2021.4.13
  - cachetools=4.2.1
  - certifi=2020.12.5
  - cffi=1.14.5
  - chardet=3.0.4
  - click=7.1.2
  - colorama=0.4.4
  - coverage=5.5
  - cryptography=2.9.2
  - cudatoolkit=10.2.89
  - cython=0.29.23
  - docutils=0.17
  - flaky=3.7.0
  - google-auth=1.28.1
  - google-auth-oauthlib=0.4.2
  - grpcio=1.36.1
  - idna=2.10
  - imagesize=1.2.0
  - importlib-metadata=3.10.0
  - iniconfig=1.1.1
  - intel-openmp=2020.2
  - isort=5.8.0
  - jinja2=2.11.3
  - joblib=1.0.1
  - lazy-object-proxy=1.6.0
  - ld_impl_linux-64=2.33.1
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libprotobuf=3.14.0
  - libstdcxx-ng=9.1.0
  - libuv=1.40.0
  - markdown=3.3.4
  - markupsafe=1.1.1
  - mccabe=0.6.1
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.0.2
  - more-itertools=8.7.0
  - multidict=5.1.0
  - ncurses=6.2
  - ninja=1.10.2
  - numpy=1.19.2
  - numpy-base=1.19.2
  - numpydoc=1.1.0
  - oauthlib=3.1.0
  - openssl=1.1.1k
  - packaging=20.9
  - pandas=1.2.4
  - pip=21.0.1
  - pluggy=0.13.1
  - protobuf=3.14.0
  - py=1.10.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.20
  - pygments=2.8.1
  - pyjwt=2.0.1
  - pylint=2.7.4
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pysocks=1.7.1
  - pytest=6.2.3
  - pytest-cov=2.11.1
  - python=3.9.4
  - python-dateutil=2.8.1
  - pytorch=1.8.1
  - pytz=2021.1
  - readline=8.1
  - requests=2.25.1
  - requests-oauthlib=1.3.0
  - rsa=4.7.2
  - scikit-learn=0.24.1
  - scipy=1.6.2
  - setuptools=52.0.0
  - six=1.15.0
  - snowballstemmer=2.1.0
  - sphinx=3.5.3
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=1.0.3
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.4
  - sqlite=3.35.4
  - tabulate=0.8.9
  - tensorboard=2.4.0
  - tensorboard-plugin-wit=1.6.0
  - threadpoolctl=2.1.0
  - tk=8.6.10
  - toml=0.10.2
  - tqdm=4.59.0
  - typing-extensions=3.7.4.3
  - typing_extensions=3.7.4.3
  - tzdata=2020f
  - urllib3=1.26.4
  - werkzeug=1.0.1
  - wheel=0.36.2
  - wrapt=1.12.1
  - xz=5.2.5
  - yarl=1.6.3
  - zipp=3.4.1
  - zlib=1.2.11
  - pip:
    - bravado==11.0.3
    - bravado-core==5.17.0
    - configparser==5.0.2
    - docker-pycreds==0.4.0
    - docopt==0.6.2
    - fire==0.4.0
    - future==0.18.2
    - gitdb==4.0.7
    - gitpython==3.1.14
    - jsonpickle==1.5.2
    - jsonpointer==2.1
    - jsonref==0.2
    - jsonschema==3.2.0
    - monotonic==1.6
    - msgpack==1.0.2
    - munch==2.5.0
    - neptune-client==0.9.5
    - pathtools==0.1.2
    - pillow==8.2.0
    - promise==2.3
    - psutil==5.8.0
    - py-cpuinfo==8.0.0
    - pyrsistent==0.17.3
    - pyyaml==5.4.1
    - rfc3987==1.3.8
    - sacred==0.8.2
    - sentry-sdk==1.0.0
    - shortuuid==1.0.1
    - simplejson==3.17.2
    - smmap==4.0.0
    - strict-rfc3339==0.7
    - subprocess32==3.5.4
    - swagger-spec-validator==2.7.3
    - termcolor==1.1.0
    - wandb==0.10.26
    - webcolors==1.11.1
    - websocket-client==0.58.0
